version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/image_gallery # URI de conexión de MongoDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest  # Usamos la imagen oficial de MongoDB
    ports:
      - "27017:27017"  # Puerto de MongoDB
    volumes:
      - mongo-data:/data/db  # Volumen persistente para la base de datos

volumes:
  mongo-data:
